names = [
  "Alan Taste",
  "Álvaro González",
  "Agustín Aballay",
  "Amy Stephens",
  "Ana Pascual",
  "Ana Valdez",
  "Anabella Zurita",
  "Andres Singls",
  "Antonio Aballay",
  "Bárbara González",
  "Bautista Remondegui",
  "Benjamín Yede",
  "Brisa Gattolin",
  "Brian Rodriguez",
  "Candela Bongiorno",
  "Candela Santivañez",
  "Camila Pacheco",
  "Camila Tulian",
  "Camila Araujo",
  "Carla Castelli",
  "Carlos Quinteros",
  "Carmen Guerrero",
  "Carolina Stheli",
  "Cecilia Guillén",
  "Connie Cañete",
  "Daniel Ramirez Rios",
  "Dante Brochero",
  "Delfina Piñero",
  "Eduardo Velásquez",
  "Élida Rosales",
  "Emmanuel Ruiz",
  "Emmanuel Zárate",
  "Enzo Collado",
  "Epifania Bustamante",
  "Esteban Lemos",
  "Eugenia Svatetz",
  "Fabricio Aravena",
  "Fabricio Gatica",
  "Fabiana Pina",
  "Franco Funez",
  "Franco Gallo",
  "Facundo Salazar",
  "Felipe Remondegui",
  "Fiorella Barresi",
  "Fiorella Ramirez",
  "Flavia Johansson",
  "Florencia Levis",
  "Florencia Valdez",
  "Florencia Vega",
  "Florencia Pastor",
  "Florencia Cabrera",
  "Gabriela Juarez",
  "German Venitez",
  "Giuliano Colombo",
  "Hector Aballay",
  "Helena Fernández Dutto",
  "Ian Lucero",
  "Ignacio Tossolini",
  "Inocencia Garcia",
  "Isa Pastor",
  "Ittala Espinal",
  "Ivan Condori",
  "Jacqui Dutto",
  "Jeremías Vega",
  "Jonathan Villegas",
  "Jorge Maldonado",
  "Juan Aballay",
  "Juan Rivoire",
  "Juan Pablo Barrionuevo",
  "Julieta Aguilera",
  "Julieta Ramirez Rios",
  "Karen Aravena",
  "Kevin Aravena",
  "Laura Esquivel",
  "Laura Aballay",
  "Laura Español",
  "Leticia Rivadeneira",
  "Lorena Burgos",
  "Lourdes Arguello",
  "Lucía Astié",
  "Lucía Carrizo",
  "Luciano Rivadeneira",
  "Luciano Torres",
  "Luciano Weigun",
  "Luciana Aballay",
  "Lupe González",
  "Luz Aravena",
  "Macarena Tello",
  "Marcos Somadossi",
  "Mari Vega Torres",
  "Mario Torres",
  "María José Valdez",
  "María José Dominguez",
  "Malena Tarchini",
  "Marcos Remondegui",
  "María Pérez Maure",
  "Matías Choquevilca",
  "Matías Solari",
  "Maximiliano Tulian",
  "Micaela Blanco",
  "Micaela Condori",
  "Micaela Bustos",
  "Milena D'amario",
  "Nancy Jalil",
  "Natacha Brochero",
  "Nestor Pastor",
  "Nicolás Guillén",
  "Nicolás Iglesias",
  "Nicolás Quinteros",
  "Ornella Todini",
  "Pablo Ramirez",
  "Pamela Aguirre",
  "Patricia Misiti",
  "Paula Vargas",
  "Priscila Quinteros",
  "Raúl Guillén",
  "Rodrigo Dutto",
  "Rodrigo Espinal",
  "Rodrigo Peralta",
  "Rosaura Condat",
  "Santiago Asis",
  "Santiago Dutto",
  "Samara Ramirez Rios",
  "Selene Vera",
  "Sofía Fassi",
  "Sofía Soria",
  "Stefanía Soria",
  "Sofía Sposetti",
  "Tomás Molina",
  "Tomás Raizman",
  "Valeria López",
  "Valentina Etchegaray",
  "Verónica Farieri",
  "Victoria Dagostino",
  "Yanina Alvarenga",
  "Yesica Martínez"
]

names.each do |n|
  Guest.find_or_create_by!(name: n)
end

puts "Creados/asegurados #{names.size} invitados."
