names = [
  "Alan Taste",
  "Álvaro González",
  "Amy Stephens",
  "Anabella Zurita",
  "Andres Singls",
  "Antonio Aballay",
  "Bárbara González",
  "Bautista Remondegui",
  "Brian Rodriguez",
  "Candela Santivañez",
  "Camila Pacheco",
  "Camila Tulian",
  "Camila Araujo",
  "Carla Castelli",
  "Carlos Quinteros",
  "Carmen Guerrero",
  "Carolina Stheli",
  "Cecilia Guillén",
  "Connie Cañete",
  "Cristian Mogelos",
  "Daniel Ramirez Rios",
  "Dante Brochero",
  "Delfina Piñero",
  "Eduardo Velásquez",
  "Élida Rosales",
  "Emmanuel Ruiz",
  "Enzo Collado",
  "Epifania Bustamante",
  "Esteban Lemos",
  "Fabricio Aravena",
  "Fabricio Gatica",
  "Franco Funez",
  "Franco Gallo",
  "Facundo Salazar",
  "Felipe Remondegui",
  "Fiorella Barresi",
  "Fiorella Ramirez",
  "Florencia Levis",
  "Florencia Valdez",
  "Florencia Vega",
  "Florencia Pastor",
  "Florencia Cabrera",
  "Gabriela Juarez",
  "German Venitez",
  "Giuliano Colombo",
  "Hector Aballay",
  "Helena Fernández Dutto",
  "Ignacio Tossolini",
  "Inocencia Garcia",
  "Isa Pastor",
  "Ittala Espinal",
  "Jonathan Villegas",
  "Jorge Maldonado",
  "Juan Rivoire",
  "Juan Pablo Barrionuevo",
  "Julieta Aguilera",
  "Julieta Ramirez Rios",
  "Karen Aravena",
  "Laura Esquivel",
  "Laura Aballay",
  "Laura Español",
  "Leticia Rivadeneira",
  "Lorena Burgos",
  "Lourdes Arguello",
  "Lucía Carrizo",
  "Luciano Rivadeneira",
  "Luciano Torres",
  "Luciano Weigun",
  "Luciana Aballay",
  "Macarena Tello",
  "Marcos Somadossi",
  "Mari Vega Torres",
  "Mario Torres",
  "María José Valdez",
  "María José Dominguez",
  "Malena Tarchini",
  "Marcos Remondegui",
  "María Pérez Maure",
  "Matías Choquevilca",
  "Matías Solari",
  "Maximiliano Tulian",
  "Micaela Blanco",
  "Micaela Condori",
  "Micaela Bustos",
  "Milena D'amario",
  "Nancy Jalil",
  "Natacha Brochero",
  "Nestor Pastor",
  "Nicolás Guillén",
  "Nicolás Iglesias",
  "Ornella Todini",
  "Pablo Ramirez",
  "Pamela Aguirre",
  "Patricia Misiti",
  "Paula Vargas",
  "Priscila Quinteros",
  "Raúl Guillén",
  "Rodrigo Espinal",
  "Rodrigo Peralta",
  "Rosaura Condat",
  "Santiago Dutto",
  "Samara Ramirez Rios",
  "Sofía Fassi",
  "Sofía Soria",
  "Stefanía Soria",
  "Sofía Sposetti",
  "Tomás Molina",
  "Valeria López",
  "Valentina Etchegaray",
  "Verónica Farieri",
  "Victoria Dagostino",
  "Yanina Alvarenga",
  "Yesica Martínez"
]

names.each do |n|
  Guest.find_or_create_by!(name: n)
end

puts "Creados/asegurados #{names.size} invitados."
